apiVersion: v1
kind: Secret
metadata:
  name: deployment-git-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/[GITHUB_REPO_HERE]
  username: [GITHUB_USERNAME_HERE]
  password: [GITHUB_PAT_HERE]
