apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-deployment
  labels:
    app: http
spec:
  replicas: 1
  strategy:
        type: RollingUpdate
        rollingUpdate:
           maxSurge: 1
  selector:
     matchLabels:
       app: http
  template:
    metadata:
      labels:
        app: http

    spec:
     containers:
        - name: http
          image: httpd
          imagePullPolicy: Always
          ports:
            - containerPort: 80
